import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

const popinsFont = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Erik Bank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={popinsFont.className}>{children}</body>
    </html>
  );
}
